Build with node 14
zooniverse/pandora pull request #168
Opened 2020-11-23 14:29 UTC by eatyourgreens

Use a node:14 image to run builds. Note that builds fail with node:14-alpine because gcc isn't installed.

2020-11-24 17:02 UTC, eatyourgreens commented
The node 14 webpack build warns about circular depencies.
```
+ npm run --silent stage
(node:55) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:55) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:55) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:55) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:55) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:55) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
Hash: 9d053c8b991abf231344
```

Despite that, the page builds and deploys to https://pandora.zooniverse.org so node 14 seems to work.

2021-03-15 21:17 UTC, srallen requested changes
Node version for travis needs updating unless you'd like to tackle migrating that to a GA.

2021-03-15 21:17 UTC, srallen commented on package.json
> +    "node": ">=10",
Let's not indicate support for an unsupported node version. 
```suggestion
    "node": ">=14",
```

2021-03-15 21:19 UTC, srallen commented
Actually we got tests in a GA in #178, so rather this PR could remove the travis config?

2021-03-15 21:19 UTC, eatyourgreens commented
Pandora doesn’t have any tests. Maybe I should just remove the Travis setup?

2021-03-17 17:22 UTC, srallen requested changes
Let's remove the travis config and I think this is good to go

2021-03-18 17:15 UTC, eatyourgreens commented
Turns out you can delete files, and commit the delete, directly through the GitHub site. That's handy.

2021-03-19 19:45 UTC, srallen approved these changes

2021-03-20 19:09 UTC, merged